## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here

# Q1-1
import pandas as pd
df = pd.DataFrame(data)
df[(df.job.isin(['teacher','psychologist']))] 

# Q1-2
df[((df.job=='teacher') | (df.job == 'psychologist')) & (df.num_cars>df.family_size)]

# Q1-3
df[(df.num_cars>=1) & (df.family_size<= 2)]

# Q1-4
num_uni_job = len(pd.unique(df['job']))
print(num_uni_job)

4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here
summary = pd.concat([fruit,weights], axis =1)
summary.groupby(0)[1].mean()

0
apple     4.8
banana    5.5
carrot    9.0
Name: 1, dtype: float64

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [2]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [8]:
# Type your solution here

# Q3-1
course_name_copy = course_name.copy()
course_name_copy.sort()
for x in course_name:
  print(x," --- ", str(np.where(course_name_copy == x)))


# Q3-2
for i in course_name:
  print(str(i) + " in course_name array starts with \"P\": " + str(i[0]!="P"))


Python  ---  (array([2]),)
JS  ---  (array([0]),)
examples  ---  (array([3]),)
PHP  ---  (array([1]),)
html  ---  (array([4]),)
Python in course_name array starts with "P": False
JS in course_name array starts with "P": True
examples in course_name array starts with "P": True
PHP in course_name array starts with "P": False
html in course_name array starts with "P": True


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Type your solution here

# Q4-1
print(student_id)
print(np.flip(student_id))

# Q4-2
student_id.sort()
print(student_id[-3:])

[1023 1671 1682 4532 5202 5241 6230]
[6230 5241 5202 4532 1682 1671 1023]
[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here
import numpy as np
num = np.arange(1,100)
sum = 0
for i in num:
  if i % 3 == 0 or i % 5 == 0:
    sum += i
print("sum = " + str(sum))
# Hint: you can use arange to start off

sum = 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Type your solution here

# Q6.1
arr1 = arr.copy()
arr1[:,[1,2]] = arr1[:,[2,1]]
print(arr1)
# Q6.2
arr2 = arr.copy()
arr2[[0,1],:] = arr2[[1,0],:]
print(arr2)

[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
